spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/gym_crm_system
  profiles:
    active: dev
  # Hibernate-specific transaction configuration
  jpa:
    open-in-view: false
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: gym-crm-system
  activemq:
    user: test
    password: test
    broker-url: tcp://localhost:61616
    packages:
      trust-all: true
# JWT
security:
  token:
    access:
      secret-key: psofsdjfsdlkfkasdnfasdifjasdfjlasdkjflaksdjf
      time: 2000000000
    refresh:
      secret-key: dijfalsjdkfaosifjsoidfkasljdflksajflkasjflasj
      time: 200000000

management:
  health:
    db:
      enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics

cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "Authorization,Content-Type"
  allow-credentials: true

messaging:
  queues:
    trainerWorkloadQueue: trainer.workload.queue


resilience4j:
  circuitbreaker:
    instances:
      trainerWorkloadCB:
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - org.springframework.cloud.client.circuitbreaker.NoFallbackAvailableException
      traineeCB:
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - org.springframework.cloud.client.circuitbreaker.NoFallbackAvailableException