server:
  port: 8080

# DataSource
datasource:
  url: jdbc:postgresql://localhost:5430/postgres?currentSchema=gym_crm_system_prod
  username: postgres
  password: bestuser

# Hibernate-specific transaction configuration
spring:
  jpa:
    open-in-view: false

# JWT
security:
  token:
    access:
      secret-key: psofsdjfsdlkfkasdnfasdifjasdfjlasdkjflaksdjf
      time: 2000000000
    refresh:
      secret-key: dijfalsjdkfaosifjsoidfkasljdflksajflkasjflasj
      time: 200000000

management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
